### ISSUE TITLE
Using pip3 instead of pip

### ISSUE THREAD

**Issue by tadwhitaker** [we45/ZAP-Mini-Workshop#1]
When running **pip install -r requirements.txt** I kept get an error saying **No matching distribution found for ipython==6.2.1 (from -r requirements.txt (line 10))**. Substituting pip3 worked.

**Comment by abhaybhargav** [comment]
Thanks for letting me know @tadwhitaker. Changed instructions to reflect this: [here](https://github.com/we45/ZAP-Mini-Workshop/commit/3384f58c7028e145000251c1eecdad06ed5e7330)

**Comment by abhaybhargav** [comment]
BTW, I still need to add more content to this. Should be closing it in 2-3 days
